export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const WORK_SPACE_LIST = 'WORK_SPACE_LIST';
export const JWT_TOKEN = 'JWT_TOKEN';
export const SELECTED_WORKSPACE = 'SELECTED_WORKSPACE';

export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';
export const ADD_WORK_SPACE = 'ADD_WORK_SPACE';
export const GET_WORKSPACE_TYPES = 'GET_WORKSPACE_TYPES';
export const GET_ALL_WORKSPACES = 'GET_ALL_WORKSPACES';
export const GET_ALL_TEAMS = 'GET_ALL_TEAMS';

export const GET_NEW_TEAM = 'GET_NEW_TEAM';
